apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dataset-gmw-v3
  namespace: argo
spec:
  entrypoint: workflow-entrypoint
  serviceAccountName: argo-workflow-sa
  podGC:
    strategy: OnWorkflowCompletion
  ttlStrategy:
    secondsAfterCompletion: 300
  podMetadata:
    annotations:
      karpenter.sh/do-not-disrupt: "true"
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  arguments:
    parameters:
      - name: image-name
        value: 891612567384.dkr.ecr.ap-southeast-2.amazonaws.com/csdr/csdr-cloud-spatial
      - name: image-tag
        value: latest
      - name: source-location
        value: https://zenodo.org/records/6894273/files/gmw_v3_1996_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2007_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2008_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2009_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2010_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2015_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2016_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2017_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2018_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2019_gtiff.zip?download=1,https://zenodo.org/records/6894273/files/gmw_v3_2020_gtiff.zip?download=1
      - name: target-bucket
        value: csdr-public-dev
      - name: target-bucket-path
        value: datasets/gmw-v3/0-0-1/
      - name: overwrite
        value: --no-overwrite  # Can be --overwrite or --no-overwrite

  templates:
    - name: workflow-entrypoint
      dag:
        tasks:
          - name: cache-zipfile
            template: cache
            arguments:
              parameters:
                - name: source-location
                  value: "{{ workflow.parameters.source-location}}"
                - name: target-bucket
                  value: "{{ workflow.parameters.target-bucket }}"
                - name: target-bucket-path
                  value: "{{ workflow.parameters.target-bucket-path }}"
                - name: overwrite
                  value: "{{ workflow.parameters.overwrite }}"

          - name: list-file-names
            depends: cache-zipfile.Succeeded
            template: list
            arguments:
              parameters:
                - name: file-names
                  value: "{{ tasks.cache-zipfile.outputs.parameters.file-names }}"

          - name: extract-files
            depends: list-file-names.Succeeded
            template: extract
            arguments:
              parameters:
                - name: bucket
                  value: "{{ workflow.parameters.target-bucket }}"
                - name: bucket-path
                  value: "{{ workflow.parameters.target-bucket-path }}"
                - name: file-name
                  value: "{{ item }}"
                - name: overwrite
                  value: "{{ workflow.parameters.overwrite }}"
            withParam: "{{ tasks.list-file-names.outputs.result }}"

          - name: create-geoparquet
            depends: extract-files.Succeeded
            template: index
            arguments:
              parameters:
                - name: bucket
                  value: "{{ workflow.parameters.target-bucket }}"
                - name: bucket-path
                  value: "{{ workflow.parameters.target-bucket-path }}"
                - name: overwrite
                  value: "{{ workflow.parameters.overwrite }}"

          - name: generate-provenance
            depends: create-geoparquet.Succeeded
            template: provenance
            arguments:
              parameters:
                - name: bucket
                  value: "{{ workflow.parameters.target-bucket }}"
                - name: bucket-path
                  value: "{{ workflow.parameters.target-bucket-path }}"
                - name: overwrite
                  value: "{{ workflow.parameters.overwrite }}"

    - name: cache
      inputs:
        parameters:
          - name: source-location
          - name: target-bucket
          - name: target-bucket-path
          - name: overwrite
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: 500Mi
            cpu: 1
        command: [csdr]
        args:
          - gmw
          - cache
          - --source-location={{ inputs.parameters.source-location }}
          - --target-location
          - "s3://{{ inputs.parameters.target-bucket }}/{{ inputs.parameters.target-bucket-path }}/raw"
          - --out-file
          - /tmp/cached_files.json
          - "{{ inputs.parameters.overwrite }}"
      outputs:
        parameters:
          - name: file-names
            valueFrom:
              path: /tmp/cached_files.json

    - name: list
      inputs:
        parameters:
          - name: file-names
      script:
        image: python:3.8
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        command: [python]
        source: |
          import json

          file_names=[]
          files = {{ inputs.parameters.file-names }}
          for file in files:
            file_name = file.rsplit('/', 1)[-1]
            file_names.append(file_name)

          print(json.dumps(file_names))

    - name: extract
      inputs:
        parameters:
          - name: bucket
          - name: bucket-path
          - name: file-name
          - name: overwrite
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: 8Gi
            cpu: 4
        command: [csdr]
        args:
          - gmw
          - extract
          - --source-location
          - "s3://{{ inputs.parameters.bucket }}/{{ inputs.parameters.bucket-path }}/raw"
          - --source-zip-name
          - "{{ inputs.parameters.file-name }}"
          - --target-location
          - "s3://{{ inputs.parameters.bucket }}/{{ inputs.parameters.bucket-path }}/data"
          - "{{ inputs.parameters.overwrite }}"

    - name: index
      inputs:
        parameters:
          - name: bucket
          - name: bucket-path
          - name: overwrite
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2Gi
            cpu: 2
        command: [csdr]
        args:
          - gmw
          - index
          - --source-location
          - "s3://{{ inputs.parameters.bucket }}/{{ inputs.parameters.bucket-path }}/data"
          - --target-location
          - "s3://{{ inputs.parameters.bucket }}/{{ inputs.parameters.bucket-path }}"
          - "{{ inputs.parameters.overwrite }}"

    - name: provenance
      inputs:
        parameters:
          - name: bucket
          - name: bucket-path
          - name: overwrite
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: 500Mi
            cpu: 1
        command: [csdr]
        args:
          - provenance
          - dataset
          - --id
          - "gmw-ame-global-v4"
          - --dataset-url
          - "s3://{{ inputs.parameters.bucket }}/{{ inputs.parameters.bucket-path }}/gmw.parquet"
          - --dataset-type
          - "stac-geoparquet"
          - --source-metadata-url
          - "https://zenodo.org/records/12756047"
          - --source-url
          - "https://zenodo.org/records/12756047"
          - "{{ inputs.parameters.overwrite }}"
