# Aggregator pipeline for all geometry processing stages
stages:
  datasets:
    cmd: cd datasets && dvc repro && cd ../../
    deps:
      - datasets/dvc.lock
  geometries:
    cmd: cd geometries && dvc repro && cd ../../
    deps:
      - geometries/dvc.lock
