# These values will be included in the provenance file
out_s3_path: s3://csdr-dev-env-data-ap-southeast-2/gmw_zonal_stats_ste.parquet
asgs_abs_geoparquet_path: s3://csdr-dev-env-data-ap-southeast-2/asgs-ste-2021.parquet
gmw_zarr_path: s3://csdr-dev-env-data-ap-southeast-2/gmw-v4019-1km-mollweide.zarr
zonal_stats:
  - stat: sum
    mode: area
    name: total_area
  - stat: mean
    mode: pixel
    name: percent_cover
