# Pipeline specific to Allen Coral Atlas (region subset)

# Internal variables
vars:
  - source_zarr: s3://files.auspatious.com/unsw/aca.zarr

stages:
  sync_zarr:
    cmd: >
      if [[ ${out_s3_path} == s3://* ]]; then
      aws s3 sync ${source_zarr} ${out_s3_path} --quiet;
      else
      echo "out_s3_path does not start with s3://, skipping upload" &&
      aws s3 sync ${source_zarr} ${out_s3_path} --quiet;
      fi

    outs:
      - ${out_s3_path}:
          cache: false
