# Pipeline specific to Allen Coral Atlas (region subset)

# Internal variables
vars:
  - source_zarr: s3://files.auspatious.com/unsw/aca.zarr

stages:
  sync_zarr:
    cmd: >-
      aws s3 sync ${source_zarr} ${out_s3_path} --quiet;
    deps:
      - ${source_zarr}
    outs:
      - ${out_s3_path}:
          cache: false
