# Pipeline specific to Tayaritja Seagrass (TSG)

# Internal variables
vars:
  - geotiff_name: nesp36_seagrass_baseline.tif
  - download_dir: in/geotiffs
  - zarr_output: out/nesp36_seagrass_baseline.zarr

stages:
  download_tsg:
    desc: Download TSG raw model layers GeoTIFF
    cmd: |
      mkdir -p ${download_dir}
      echo "Downloading from ${url}..."
      curl -L -o ${download_dir}/${geotiff_name} "${url}"
    outs:
      - ${download_dir}:
          cache: false

  raster_to_zarr_tsg:
    cmd: >-
      csdr datasets raster-to-zarr
      --input-raster ${download_dir}/${geotiff_name}
      --output-zarr ${zarr_output}
    deps:
      - ${download_dir}

      - ../../csdr/cli_datasets.py
    outs:
      - ${zarr_output}:
          cache: false

  validate_tsg:
    cmd: >-
      csdr datasets validate-zarr --input-zarr ${zarr_output}
    deps:
      - ${zarr_output}

      - ../../csdr/cli_datasets.py

  upload_tsg:
    cmd: >-
      if [[ ${out_s3_path} == s3://* ]]; then aws s3 cp ${zarr_output} ${out_s3_path} --recursive; else echo "out_s3_path does not start with s3://, skipping upload" && cp -r ${zarr_output} ${out_s3_path}; fi
    deps:
      - ${zarr_output}
    outs:
      - ${out_s3_path}:
          cache: false