# These values will be included in the provenance file

out_s3_path: s3://csdr-dvc-out/nesp36_seagrass_baseline.zarr
url: https://drive.google.com/uc?export=download&id=15F4qz9fHgcBN4b7UdjPTigfIfeYDggx-
target_crs: +proj=longlat +datum=WGS84 +no_defs
target_resolution: 0.0002
resampling_method: nearest
