# Pipeline specific to ASGS STE Geometries (Edition 3)

# Internal variables
# https://marineregions.org/download_file.php?name=EEZ_land_union_v4_202410.zip
vars:
  - archive_name: EEZ_land_union_v4_202410.zip
  - shapefile_name: EEZ_land_union_v4_202410.shp
  - extract_dir: in/eez-land-union
  - parquet_output: out/EEZ_land_union_v4_202410.parquet # Relative to project root

stages:
  download:
    desc: Download and extract the EEZ_land_union_v4_202410 files
    cmd: |
      mkdir -p ${extract_dir}
      echo "Downloading from ${url}..."
      curl -L -o ${extract_dir}/${archive_name} ${url}
      echo "Unzipping..."
      unzip -o ${extract_dir}/${archive_name} -d ${extract_dir}
    outs:
      - ${extract_dir}:
          cache: false # Often don't cache raw downloads/extracts if source URL is stable

  convert:
    desc: Convert extracted shapefile to GeoParquet
    cmd: >-
      csdr geometries convert-vector
      --input-dir ${extract_dir}
      --input-glob ${shapefile_name}
      --target-crs EPSG:4326
      --output-path ${parquet_output}
      --name-property ${name_property}
    # Depend on the directory from previous stage and the script
    deps:
      - ${extract_dir}

      - ../../csdr/cli_geometries.py
    # Define the output relative to the main project root
    outs:
      - ${parquet_output}:
          cache: false

  validate:
    desc: Validate the generated GeoParquet file (schema, CRS, etc.)
    cmd: >-
      csdr geometries validate
      --input-file ${parquet_output}
    deps:
      - ${parquet_output} # Depends on the converted file

      - ../../csdr/cli_geometries.py

  upload:
    cmd: >-
      if [[ ${out_s3_path} == s3://* ]]; then aws s3 cp ${parquet_output} ${out_s3_path}; else echo "out_s3_path does not start with s3://, skipping upload" && cp ${parquet_output} ${out_s3_path}; fi
    deps:
      - ${parquet_output}
    outs:
      - ${out_s3_path}:
          cache: false
