# These values will be included in the provenance file
name: "aca_zonal_stats_eez"
out_s3_path: s3://csdr-dev-env-data-ap-southeast-2/aca_zonal_stats_eez.parquet
json_out_s3_path: s3://csdr-dev-env-data-ap-southeast-2/aca_zonal_stats_eez/
eez_geoparquet_path: s3://csdr-dev-env-data-ap-southeast-2/EEZ_land_union_v4_202410.parquet
aca_zarr_path: s3://csdr-dev-env-data-ap-southeast-2/aca.zarr
zonal_stats:
  - stat: sum
    mode: area
    name: total_area
