# Pipeline specific to Global Mangrove Watch (GMW)

# Internal variables
vars:
  - archive_name: gmw_mng_2020_v4019_gtiff.zip
  - extract_dir: in/geotiffs
  - projected_dir: in/projected-geotiffs
  - vrt_path: in/projected-geotiffs.vrt
  - zarr_output: out/gmw-v4019-1km-mollweide.zarr

stages:
  download_extract_gmw:
    desc: Download and extract GMW GeoTIFF archive
    cmd: |
      mkdir -p ${extract_dir}
      echo "Downloading from ${url}..."
      curl -L -o ${extract_dir}/${archive_name} "${url}"
      echo "Unzipping..."
      unzip -o ${extract_dir}/${archive_name} -d ${extract_dir}
    outs:
      - ${extract_dir}:
          cache: false

  warp_gmw:
    cmd: >-
      csdr datasets warp-raster
      --input-dir "${extract_dir}"
      --output-dir "${projected_dir}"
      --target-crs "${target_crs}"
      --target-resolution "${target_resolution}"
      --resampling-method "${resampling_method}"
    deps:
      - ${extract_dir}
      # Dependency on the main CLI script
      - ../../csdr/cli_datasets.py # Dependency on the datasets script
    outs:
      - ${projected_dir}:
          cache: false

  build_vrt_gmw:
    cmd: |
      echo "Building VRT: ${vrt_path}"
      gdalbuildvrt ${vrt_path} ${projected_dir}/*.tif
    deps:
      - ${projected_dir} # Depends on the output directory of the warp stage
    outs:
      - ${vrt_path}

  vrt_to_zarr_gmw:
    cmd: >-
      csdr datasets raster-to-zarr
      --input-raster ${vrt_path}
      --output-zarr ${zarr_output}
    deps:
      - ${vrt_path}

      - ../../csdr/cli_datasets.py
    outs:
      - ${zarr_output}:
          cache: false

  validate_gmw:
    cmd: >-
      csdr datasets validate-zarr --input-zarr ${zarr_output}
    deps:
      - ${zarr_output} # Depends on the converted file

      - ../../csdr/cli_datasets.py

  upload_gmw:
    cmd: >-
      if [[ ${out_s3_path} == s3://* ]]; then aws s3 cp ${zarr_output} ${out_s3_path} --recursive; else echo "out_s3_path does not start with s3://, skipping upload" && cp -r ${zarr_output} ${out_s3_path}; fi
    deps:
      - ${zarr_output}
    outs:
      - ${out_s3_path}:
          cache: false
