# These values will be included in the provenance file

out_s3_path: s3://csdr-dvc-out/gmw-v4019-1km-mollweide.zarr
url: https://zenodo.org/records/12756047/files/gmw_mng_2020_v4019_gtiff.zip?download=1
# Resample/Reproject from 0.0001 degree resolution (WGS84) to 1km resolution (Mollweide)
target_crs: +proj=moll +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
target_resolution: 1000
resampling_method: nearest
